export const CSS_CLASSES = {
    CONTAINER: 'container',
    BUILDING: 'building',
    BUILDING_CONTAINER: 'building-container',
    BUILDING_TITLE: 'building-title',
    BUILDING_WRAPPER: 'building-wrapper',
    FLOOR: 'floor',
    FLOOR_NUMBER: 'floor-number',
    ELEVATOR: 'elevator',
    ELEVATOR_CONTAINER: 'elevator-container',
    BUTTON: 'floor-button',
    PRESSED: 'pressed',
    COUNTDOWN: 'countdown',
    SETTINGS_PANEL: 'settings-panel',
    SETTINGS_OVERLAY: 'settings-overlay',
    SETTINGS_TOGGLE: 'settings-toggle',
    SETTINGS_GROUP: 'settings-group',
    APPLY_BUTTON: 'apply-button',
    VISIBLE: 'visible',
};